### ISSUE TITLE
Can not python social_mapper

### ISSUE THREAD

**Issue by Cvrew** [Greenwolf/social_mapper#105]
I tried this, (image is folder that has image.jpg)

pwd
/home/ubuntu/san/social_mapper

python social_mapper.py -f imagefolder -i /home/ubuntu/san/social_mapper/image -m fast -a
/home/ubuntu/.local/lib/python2.7/site-packages/bs4/element.py:16: UserWarning: The soupsieve package is not installed. CSS selectors cannot be used.
'The soupsieve package is not installed. CSS selectors cannot be used.'
[-] Error Filling out Facebook Profiles [-]
Message: 'geckodriver' executable needs to be in PATH.

[-]
Traceback (most recent call last):
File "social_mapper.py", line 1112, in
peoplelist = fill_twitter(peoplelist)
File "social_mapper.py", line 218, in fill_twitter
TwitterfinderObject = twitterfinder.Twitterfinder(showbrowser)
File "/home/ubuntu/san/social_mapper/modules/twitterfinder.py", line 19, in init
self.driver = webdriver.Firefox()
File "/home/ubuntu/.local/lib/python2.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 164, in init
self.service.start()
File "/home/ubuntu/.local/lib/python2.7/site-packages/selenium/webdriver/common/service.py", line 83, in start
os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH. 
What should do?

**Comment by 12mta** [comment]
move the gecko driver to the bin

**Comment by Cvrew** [comment]
I try 
"sudo mv geckodriver /usr/local/bin"
But error still displayed.

**Comment by Greenwolf** [comment]
Hi @Cvrew, looks like your missing a package, did you use pip install? Can you try on Kali instead of Ubuntu, just in case an update broke something it relies on.

**Comment by Cvrew** [comment]
I installed pip "sudo apt-get install python-pip". 
But erorr still displayed.

**Comment by Cvrew** [comment]
I moved geckodriver to /usr/bin/, another eorror displayed. 
python social_mapper.py -f imagefolder -i /home/ubuntu/san/social_mapper/image -m fast -a
/home/ubuntu/.local/lib/python2.7/site-packages/bs4/element.py:16: UserWarning: The soupsieve package is not installed. CSS selectors cannot be used.
  'The soupsieve package is not installed. CSS selectors cannot be used.'

[+] Facebook Login Page loaded successfully [+]
[-] Facebook Login Failed [-]

Facebook Check 1/1 : Bill Gates                                
Facebook session has expired attempting to reestablish...

[+] Facebook Login Page loaded successfully [+]
[-] Facebook Login Failed [-]

Facebook Timeout Error, session has expired and attempts to reestablish have failed

[+] Twitter Login Page loaded successfully [+]
[-] Twitter Login Failed [-]

Twitter Check 1/1 : Bill Gates                                
[+] Instagram Login Page loaded successfully [+]
[-] Instagram Login Failed [-]

Instagram Check 1/1 : Bill Gates                                
[+] Instagram Login Page loaded successfully [+]
[-] Instagram Login Failed [-]

Instagram Timeout Error, session has expired and attempts to reestablish have failed

[+] LinkedIn Login Page loaded successfully [+]
[-] LinkedIn Login Failed [-]

LinkedIn Check 1/1 : Bill Gates                                
[+] LinkedIn Login Page loaded successfully [+]
[-] LinkedIn Login Failed [-]

LinkedIn Timeout Error, session has expired and attempts to reestablish have failed

[+] Google Login Page Part 1 loaded successfully [+]
GooglePlus Check 1/1 : Bill Gates                                
[+] VKontakte Login Page loaded successfully [+]
[-] Vkontakte Login Failed [-]

VKontakte Check 1/1 : Bill Gates                                
[+] Weibo Login Page loaded successfully [+]
[+] Weibo Login Success [+]

Weibo Check 1/1 : Bill Gates                                
[+] Douban Login Page loaded successfully [+]
Traceback (most recent call last):
  File "social_mapper.py", line 1143, in <module>
    peoplelist = fill_douban(peoplelist)
  File "social_mapper.py", line 707, in fill_douban
    DoubanfinderObject.doLogin(douban_username,douban_password)
  File "/home/ubuntu/san/social_mapper/modules/doubanfinder.py", line 33, in doLogin
    wbUsername = self.driver.find_element_by_id("email")
  File "/home/ubuntu/.local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 360, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/home/ubuntu/.local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: [id="email"]

**Comment by Greenwolf** [comment]
Hi @Cvrew, sorry about the delay, i've been quite busy. If you're still having issues i would suggest trying a completely fresh install and following the instructions to the letter. Just incase something have changed on Ubuntu, why don't you give it a go on a Kali to see if it works for you?

**Comment by Cvrew** [comment]
OK. I try.

**Comment by Greenwolf** [comment]
Assuming that you managed to get it working on kali, if not let me know. Closing for now.

**Comment by deadfishhackers** [comment]
open it, soupsieve is not installed it says

**Comment by coercion420** [comment]
I get the same error on Kali. Any help?

**Comment by Greenwolf** [comment]
You could try uninstalling soupsieve and reinstalling Beautifulsoup (which contains soupsieve i believe)? I've never had this issue though 🤔
