### ISSUE TITLE
If I do not know the name of the person I research, can I not find out?

### ISSUE THREAD

**Issue by Cvrew** [Greenwolf/social_mapper#107]
If social_mapper did not know the real name in the photo we are researching, if it was a suitable name, can not we are researching, if it was a suitable name, can not we identify it? 
If so, do I need to enter special commands? (If you have one, please let me know)

**Comment by Greenwolf** [comment]
Hi @Cvrew, for social mapper to work it needs a linked list of Name + Photo, so it can do a lookup via name then identify the correct profile via facial recognition. It can't just search by photo.

**Comment by Cvrew** [comment]
OK. I understoood. 
Are you planning to develop it so that I can search for it only with face photos? I want to search without a name.

**Comment by Greenwolf** [comment]
Hi CVrew, this is not possible and won't be implemented
