### ISSUE TITLE
Instagram Login Page title field have changed

### ISSUE THREAD

**Issue by janmei** [Greenwolf/social_mapper#115]
Hey, 

i got the error message that the login page title has changed on the Instagram page:
`Instagram Login Page title field seems to have changed, please ...`

When running with Firefox, it goes straight to `instagram.com` and not `instagram.com/accounts/login` like it should do according to the code.

Can fix that issue? 

Thanks

**Comment by janmei** [comment]
Found the Issue. 
Instagram Title changes based on User Location and adjusts in Location Language. 

Changed in in `title.startswith("Login");`

Same issue with the search field. Needs to bee looked up with inspector and then changed in code to match the placeholder.

**Comment by kix-s** [comment]
it can fix easily, you can go /socail_mapper/moduels, find instagram moduels and edit this.

Find this(use Ctrl + F) "https://www.instagram.com/accounts/login/" and replace "https://www.instagram.com/accounts/login/?hl=en"


**/?hl=en** this can be automatic change youre native language to English

**Comment by Greenwolf** [comment]
Excellent tip, thank you @kix-s, i've added you to contributors
