### ISSUE TITLE
Pillow error

### ISSUE THREAD

**Issue by altaycivan** [Greenwolf/social_mapper#116]
Collecting scandir; python_version < "3.5" (from pathlib2; python_version == "2.7" or python_version == "3.3"->ipython->-r requirements.txt (line 13))
  Downloading https://files.pythonhosted.org/packages/df/f5/9c052db7bd54d0cbf1bc0bb6554362bba1012d03e5888950a4f5c5dadc4e/scandir-1.10.0.tar.gz
Installing collected packages: backports.functools-lru-cache, soupsieve, beautifulsoup4, urllib3, selenium, EasyProcess, pyvirtualdisplay, tabulate, certifi, chardet, idna, requests, numpy, Click, face-recognition-models, Pillow, dlib, face-recognition, pytz, django, scipy, cycler, kiwisolver, pyparsing, python-dateutil, subprocess32, matplotlib, PyWavelets, cloudpickle, toolz, dask, decorator, networkx, scikit-image, scikit-learn, pygments, wcwidth, prompt-toolkit, backports.shutil-get-terminal-size, scandir, pathlib2, pickleshare, ipython-genutils, traitlets, ptyprocess, pexpect, simplegeneric, ipython, facebook-sdk
  Running setup.py install for tabulate ... done
  Found existing installation: idna 2.2
    Not uninstalling idna at /usr/lib/python2.7/dist-packages, outside environment /usr
  Running setup.py install for numpy ... //Users/d1done
  Running setup.py install for face-recognition-models ... done
  Running setup.py install for Pillow ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-kqeHWO/Pillow/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-CQ4OaU-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-aarch64-2.7
    creating build/lib.linux-aarch64-2.7/PIL
    copying src/PIL/Jpeg2KImagePlugin.py -> build/lib.linux-aarch64-2.7/PIL
    copying src/PIL/PalmImagePlugin.py -> build/lib.linux-aarch64-2.7/PIL
    copying src/PIL/BlpImagePlugin.py -> build/lib.linux-aarch64-2.7/PIL
    copying src/PIL/ImageColor.py -> build/lib.linux-aarch64-2.7/PIL
    copying src/PIL/ImageFile.py -> build/lib.linux-aarch64-2.7/PIL
    copying src/PIL/ImageDraw.py -> build/lib.linux-aarch64-2.7/PIL
    copying src/PIL/IcnsImagePlugin.py -> build/lib.linux-aarch64-2.7/PIL
    copying src/PIL/ImageChops.py -> build/lib.linux-aarch64-2.7/PIL
    copying src/PIL/ImageOps.py -> build/lib.linux-aarch64-2.7/PIL
    copying src/PIL/XpmImagePlugin.py -> build/lib.linux-aarch64-2.7/PIL
    copying src/PIL/BufrStubImagePlugin.py -> build/lib.linux-aarch64-2.7/PIL
    copying src/PIL/ImageMorph.py -> build/lib.linux-aarch64-2.7/PIL
    copying src/PIL/TgaImagePlugin.py -> build/lib.linux-aarch64-2.7/PIL
    copying src/PIL/PdfImagePlugin.py -> build/lib.linux-aarch64-2.7/PIL
    copying src/PIL/GdImageFile.py -> build/lib.linux-aarch64-2.7/PIL
    copying src/PIL/FliImagePlugin.py -> build/lib.linux-aarch64-2.7/PIL
    copying src/PIL/GbrImagePlugin.py -> build/lib.linux-aarch64-2.7/PIL
    copying src/PIL/Image.py -> build/lib.linux-aarch64-2.7/PIL
    copying src/PIL/_version.py -> build/lib.linux-aarch64-2.7/PIL
    copying src/PIL/FtexImagePlugin.py -> build/lib.linux-aarch64-2.7/PIL
    copying src/PIL/PsdImagePlugin.py -> build/lib.linux-aarch64-2.7/PIL
    copying src/PIL/BdfFontFile.py -> build/lib.linux-aarch64-2.7/PIL
    copying src/PIL/ImtImagePlugin.py -> build/lib.linux-aarch64-2.7/PIL
    copying src/PIL/TiffTags.py -> build/lib.linux-aarch64-2.7/PIL
    copying src/PIL/DcxImagePlugin.py -> build/lib.linux-aarch64-2.7/PIL
    copying src/PIL/IcoImagePlugin.py -> build/lib.linux-aarch64-2.7/PIL
    copying src/PIL/MpegImagePlugin.py -> build/lib.linux-aarch64-2.7/PIL
    copying src/PIL/WebPImagePlugin.py -> build/lib.linux-aarch64-2.7/PIL
    copying src/PIL/_tkinter_finder.py -> build/lib.linux-aarch64-2.7/PIL
    copying src/PIL/ImageCms.py -> build/lib.linux-aarch64-2.7/PIL
    copying src/PIL/ImageShow.py -> build/lib.linux-aarch64-2.7/PIL
    copying src/PIL/PngImagePlugin.py -> build/lib.linux-aarch64-2.7/PIL
    copying src/PIL/PcfFontFile.py -> build/lib.linux-aarch64-2.7/PIL
    copying src/PIL/MspImagePlugin.py -> build/lib.linux-aarch64-2.7/PIL
    copying src/PIL/EpsImagePlugin.py -> build/lib.linux-aarch64-2.7/PIL
    copying src/PIL/FpxImagePlugin.py -> build/lib.linux-aarch64-2.7/PIL
    copying src/PIL/TarIO.py -> build/lib.linux-aarch64-2.7/PIL
    copying src/PIL/ImageFilter.py -> build/lib.linux-aarch64-2.7/PIL
    copying src/PIL/MpoImagePlugin.py -> build/lib.linux-aarch64-2.7/PIL
    copying src/PIL/ImImagePlugin.py -> build/lib.linux-aarch64-2.7/PIL
    copying src/PIL/GimpPaletteFile.py -> build/lib.linux-aarch64-2.7/PIL
    copying src/PIL/PixarImagePlugin.py -> build/lib.linux-aarch64-2.7/PIL
    copying src/PIL/XVThumbImagePlugin.py -> build/lib.linux-aarch64-2.7/PIL
    copying src/PIL/IptcImagePlugin.py -> build/lib.linux-aarch64-2.7/PIL
    copying src/PIL/WmfImagePlugin.py -> build/lib.linux-aarch64-2.7/PIL
    copying src/PIL/TiffImagePlugin.py -> build/lib.linux-aarch64-2.7/PIL
    copying src/PIL/ExifTags.py -> build/lib.linux-aarch64-2.7/PIL
    copying src/PIL/ImageMath.py -> build/lib.linux-aarch64-2.7/PIL
    copying src/PIL/ImageStat.py -> build/lib.linux-aarch64-2.7/PIL
    copying src/PIL/ContainerIO.py -> build/lib.linux-aarch64-2.7/PIL
    copying src/PIL/PSDraw.py -> build/lib.linux-aarch64-2.7/PIL
    copying src/PIL/SgiImagePlugin.py -> build/lib.linux-aarch64-2.7/PIL
    copying src/PIL/FitsStubImagePlugin.py -> build/lib.linux-aarch64-2.7/PIL
    copying src/PIL/__init__.py -> build/lib.linux-aarch64-2.7/PIL
    copying src/PIL/MicImagePlugin.py -> build/lib.linux-aarch64-2.7/PIL
    copying src/PIL/ImageQt.py -> build/lib.linux-aarch64-2.7/PIL
    copying src/PIL/features.py -> build/lib.linux-aarch64-2.7/PIL
    copying src/PIL/PcdImagePlugin.py -> build/lib.linux-aarch64-2.7/PIL
    copying src/PIL/ImageSequence.py -> build/lib.linux-aarch64-2.7/PIL
    copying src/PIL/PcxImagePlugin.py -> build/lib.linux-aarch64-2.7/PIL
    copying src/PIL/ImagePath.py -> build/lib.linux-aarch64-2.7/PIL
    copying src/PIL/CurImagePlugin.py -> build/lib.linux-aarch64-2.7/PIL
    copying src/PIL/_util.py -> build/lib.linux-aarch64-2.7/PIL
    copying src/PIL/BmpImagePlugin.py -> build/lib.linux-aarch64-2.7/PIL
    copying src/PIL/JpegImagePlugin.py -> build/lib.linux-aarch64-2.7/PIL
    copying src/PIL/XbmImagePlugin.py -> build/lib.linux-aarch64-2.7/PIL
    copying src/PIL/PdfParser.py -> build/lib.linux-aarch64-2.7/PIL
    copying src/PIL/SunImagePlugin.py -> build/lib.linux-aarch64-2.7/PIL
    copying src/PIL/ImageMode.py -> build/lib.linux-aarch64-2.7/PIL
    copying src/PIL/SpiderImagePlugin.py -> build/lib.linux-aarch64-2.7/PIL
    copying src/PIL/ImageGrab.py -> build/lib.linux-aarch64-2.7/PIL
    copying src/PIL/JpegPresets.py -> build/lib.linux-aarch64-2.7/PIL
    copying src/PIL/FontFile.py -> build/lib.linux-aarch64-2.7/PIL
    copying src/PIL/DdsImagePlugin.py -> build/lib.linux-aarch64-2.7/PIL
    copying src/PIL/_binary.py -> build/lib.linux-aarch64-2.7/PIL
    copying src/PIL/ImageTk.py -> build/lib.linux-aarch64-2.7/PIL
    copying src/PIL/McIdasImagePlugin.py -> build/lib.linux-aarch64-2.7/PIL
    copying src/PIL/Hdf5StubImagePlugin.py -> build/lib.linux-aarch64-2.7/PIL
    copying src/PIL/GimpGradientFile.py -> build/lib.linux-aarch64-2.7/PIL
    copying src/PIL/PyAccess.py -> build/lib.linux-aarch64-2.7/PIL
    copying src/PIL/ImageEnhance.py -> build/lib.linux-aarch64-2.7/PIL
    copying src/PIL/ImagePalette.py -> build/lib.linux-aarch64-2.7/PIL
    copying src/PIL/WalImageFile.py -> build/lib.linux-aarch64-2.7/PIL
    copying src/PIL/ImageFont.py -> build/lib.linux-aarch64-2.7/PIL
    copying src/PIL/PaletteFile.py -> build/lib.linux-aarch64-2.7/PIL
    copying src/PIL/ImageDraw2.py -> build/lib.linux-aarch64-2.7/PIL
    copying src/PIL/ImageWin.py -> build/lib.linux-aarch64-2.7/PIL
    copying src/PIL/ImageTransform.py -> build/lib.linux-aarch64-2.7/PIL
    copying src/PIL/GribStubImagePlugin.py -> build/lib.linux-aarch64-2.7/PIL
    copying src/PIL/GifImagePlugin.py -> build/lib.linux-aarch64-2.7/PIL
    copying src/PIL/PpmImagePlugin.py -> build/lib.linux-aarch64-2.7/PIL
    running egg_info
    writing src/Pillow.egg-info/PKG-INFO
    writing top-level names to src/Pillow.egg-info/top_level.txt
    writing dependency_links to src/Pillow.egg-info/dependency_links.txt
    reading manifest file 'src/Pillow.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching '*.c'
    warning: no files found matching '*.h'
    warning: no files found matching '*.sh'
    no previously-included directories found matching 'docs/_static'
    warning: no previously-included files found matching '.appveyor.yml'
    warning: no previously-included files found matching '.coveragerc'
    warning: no previously-included files found matching '.codecov.yml'
    warning: no previously-included files found matching '.editorconfig'
    warning: no previously-included files found matching '.landscape.yaml'
    warning: no previously-included files found matching '.readthedocs.yml'
    warning: no previously-included files found matching 'azure-pipelines.yml'
    warning: no previously-included files found matching 'tox.ini'
    warning: no previously-included files matching '.git*' found anywhere in distribution
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*.so' found anywhere in distribution
    no previously-included directories found matching '.azure-pipelines'
    no previously-included directories found matching '.travis'
    writing manifest file 'src/Pillow.egg-info/SOURCES.txt'
    running build_ext
    
    
    The headers or library files could not be found for jpeg,
    a required dependency when compiling Pillow from source.
    
    Please see the install instructions at:
       https://pillow.readthedocs.io/en/latest/installation.html
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-kqeHWO/Pillow/setup.py", line 804, in <module>
        raise RequiredDependencyException(msg)
    __main__.RequiredDependencyException:
    
    The headers or library files could not be found for jpeg,
    a required dependency when compiling Pillow from source.
    
    Please see the install instructions at:
       https://pillow.readthedocs.io/en/latest/installation.html
    
    
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-kqeHWO/Pillow/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-CQ4OaU-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-kqeHWO/Pillow/

**Comment by Greenwolf** [comment]
Good Afternoon @altaycivan, whats OS are you using?

**Comment by Greenwolf** [comment]
Hmmm, I’m not sure how to fix this, I just tested and the code is fine, it’s likely a dependency issue. Can you try a fresh install?

**Comment by Greenwolf** [comment]
Closing this as no response and likely due to dependency problems.
