### ISSUE TITLE
Face recognition from photo to imagesUrl column on sheets

### ISSUE THREAD

**Issue by zaesarius** [Greenwolf/social_mapper#117]
Hi again!

Have been looking around Github and on google without any success. At the end think here is still the place where I could get some suggestions.

I'm trying to play around to get from one photo a face recognition into a column spreadsheet where are images URL. Is that possible?

Any suggestion?

Appreciate :pray:

**Comment by Greenwolf** [comment]
You'll always need a name + photo to do the search, unless you have a huge database of images and names already at your disposal.

**Comment by zaesarius** [comment]
Yes,

Having url images column and name.

How should I set this?

I think this can be really useful

**Comment by zaesarius** [comment]
Do you mean in one hand names and in the other photos? Or  the photos url with the name?

I'm a bit confused

**Comment by Greenwolf** [comment]
You can use urls to photos, but you need a name for each photo, see the csv input in the examples folder. Or you can use a folder of named images. 

I was just trying to say, it’s not possible to do the lookup without names, as you can’t do it with just a photo.

**Comment by zaesarius** [comment]
For example,

It is possible to extract IG posts (image + text) and put the imageUrl on column and text on other column. If text contains names + pictures url with faces it would do the recognition?

Thank you for your time :100:

**Comment by Greenwolf** [comment]
Ah I think I see what you mean. It would be possible to do something like that, but you would need to customise the code for yourself. It just works on profile pictures at the moment.

**Comment by zaesarius** [comment]
Thank you :+1:
