### ISSUE TITLE
Doesn't work with small companies, Facebook is blank

### ISSUE THREAD

**Issue by lorenzoromani1983** [Greenwolf/social_mapper#120]
I am having this issue: with small companies it does not fill any profile. Just logs into every social network but does not execute the search.

With bigger companies it does the job but "cannot identify target image" on Facebook. Facebook remains un-filled.

At the very beginning of each task, i get this:

!] Cannot load main LinkedIn page

**Comment by Greenwolf** [comment]
Hi @lorenzoromani1983, 

Could you provide some full input/example company its failing on? Do larger companies work with facebook?

**Comment by Greenwolf** [comment]
Closing this due to lack of a response. After testing small companies do seem to work for me.
