### ISSUE TITLE
LinkedIn and Douban error

### ISSUE THREAD

**Issue by limengmengha** [Greenwolf/social_mapper#122]
I don't know why this is happening,The LinkedIn  and Douban account is right, what is the problem?

[+] LinkedIn Login Page loaded successfully [+]
[+] LinkedIn Login Success [+]

LinkedIn Timeout Error, session has expired and attempts to reestablish have failed

[+] Douban Login Page loaded successfully [+]
[-] Douban Login Failed [-]

**Comment by venturaEffect** [comment]
Hi,

Try to refresh the linkedin page and look if it asks for captcha or something like this. And if it logs again try it with social_mapper.

Hope it helps... :crossed_fingers:

**Comment by Greenwolf** [comment]
I've added a 20 seconds sleep after login so you can manually enter a capatcha if needed. If you keep having problems please reopen and post more details below.

**Comment by limengmengha** [comment]
> I've added a 20 seconds sleep after login so you can manually enter a capatcha if needed. If you keep having problems please reopen and post more details below.

This problem has been resolved. A verification code is required for the first login, but it is not convenient to run the program using a remote terminal
