### ISSUE TITLE
Invalid syntax error

### ISSUE THREAD

**Issue by jkyle9810** [Greenwolf/social_mapper#123]
Hey Greenwolf,

I'm having issues running this on mac os x.

For installation step 3:
git clone https://github.com/Greenwolf/social_mapper
cd social_mapper/setup
python -m pip install --no-cache-dir -r requirements.txt

I put it in the shell, press enter, and get 'invalid syntax'

**Comment by Greenwolf** [comment]
Hi @jkyle9810, Can you post the full error please? Are you using python3?
python --version

**Comment by jkyle9810** [comment]
It’s when I was putting it in the IDLE shell.

I was running Mac OS X Lion that is too old to have Xcode installed.

Am I supposed to be putting the step 3 from the ReadMe into the IDLE shell
directly?

It was not clear from the documentation.

What are all the things that should be in the /local path?

Thanks

**Comment by Greenwolf** [comment]
@jkyle9810 not directly into python, those are OS commands.

You only need to put Geckodriver in /usr/local/bin

**Comment by jkyle9810** [comment]
Thank you. I’ll try that.

What about the Mac specific requirements?

Where are those supposed to be executed in?

**Comment by Greenwolf** [comment]
I'm sorry, but i'm not sure what you can do if your still on Mountain Lion on an old system. You might need a newer OS!

**Comment by jkyle9810** [comment]
Do I need Xcode for this to work?

**Comment by Greenwolf** [comment]
You need the xcode tools package to install certain dependencies on osx i believe. If you manage to get it working without xcode, do let me know though and i'll update the readme!
________________________________

**Comment by jkyle9810** [comment]
Can you update ReadMe to clarify what needs to be executed in IDLE vs
Geckodriver vs terminal?

I need to buy a new Mac for this purpose and want to make sure I can get
this working on it!

Thanks!

**Comment by Greenwolf** [comment]
Hey, I think there is some confusion here, all the install instructions are completed using your terminal, even the command to run python social mapper is used in this. You don't need to enter any commands into your python interpreter.
________________________________

**Comment by jkyle9810** [comment]
What about the requirements.txt file for Mac. Where is that ran from?

**Comment by Greenwolf** [comment]
Closing this as it's not an issue with social mapper, just having trouble installing it. Feel free to keep replying and i'll try to help you though. the requirements.txt file is ran in your terminal too, you just need to use the python -m pip command in the readme.
