### ISSUE TITLE
HELP tried everything but keep getting 'Unable to find a matching set of capabilities'

### ISSUE THREAD

**Issue by ethicalhackz** [Greenwolf/social_mapper#125]
Im using Linux Kali 4.19.0, Firefox quantum 68.0.1 64-bit (also tried Firefox nightmode with no luck), Python 3.7.4, Selenium 3.141.0

This is the error I keep getting

### HTML file: SM-Results/results-social-mapper.html

Ok so im praying someone can fix this because I've tried EVERYTHING I've gone through every forum. I tried using fix #19 . By Snorkeldink which gave me the same 'Unable to find a matching set of capabilities error. Everything's up to date and ive literally spent hours trying everything i can to fix this but I just cant. I really need to use social mapper though so if for some reason if just doesn't work with Kali please recommend another linux distro

**Comment by Greenwolf** [comment]
Hey @ethicalhackz, I'm super busy the next few weeks, but I'll get to this eventually. Could anyone confirm is Social Mapper is broken right now? or is this an individual install issue?

**Comment by Greenwolf** [comment]
@ethicalhackz try using Ubuntu, sometimes the install can just go wrong, so perhaps try on a fresh VM?
