### ISSUE TITLE
 "[!]Cannot load main LinkedIn page" Error because of 404 response

### ISSUE THREAD

**Issue by cyb3rwr3ck** [Greenwolf/social_mapper#126]
Hi,
it seems that `https://www.linkedin.com/checkpoint/lg/login-submit` does not accept the GET Request and answers it with a 404. It still seems to be the correct address for the POST for credentials though. 

Trace:
```
Traceback (most recent call last):
  File "social_mapper.py", line 743, in loadPage
    response = client.open(url)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
[!] Cannot load main LinkedIn page
cookie debug
```

**Comment by Museon23** [comment]
same ^

**Comment by Greenwolf** [comment]
Hi All, thank you for taking the time to raise the issue, I'll get on this as soon as I have a chance!

**Comment by pdelteil** [comment]
Same here, it's a weird behavior because even when I don't call the Linkedin parameter (-li) still raises this error.

**Comment by cyb3rwr3ck** [comment]
> Same here, it's a weird behavior because even when I don't call the Linkedin parameter (-li) still raises this error.

Thats actually intended as the first step is ALWAYS to query Linkedin. So even with deactivated Linkedin usage Linkedin break the script right now

**Comment by Greenwolf** [comment]
Hi All, if you are using the company input, it will always query LinkedIn as it is how it gathers the names and faces if you don't provide it via a csv or imagefolder. 

I'll look into this soon

**Comment by Greenwolf** [comment]
Has that fixed it?

**Comment by Greenwolf** [comment]
I think this is fixed now.

**Comment by cyb3rwr3ck** [comment]
I will check this asap
