### ISSUE TITLE
cannot identify image file 'potential_target_image.jpg'; Instagram Login Page title field seems to have change

### ISSUE THREAD

**Issue by cyvitor** [Greenwolf/social_mapper#127]
Hi!!!
i've got 2 issue! :-(
Plis help
System: Kali 2019.2

[-] Facebook Login Failed [-]
Facebook Check 1/3 : Steve Jobs                                cannot identify image file 'potential_target_image.jpg'

Instagram Check 1/3 : Steve Jobs                                Instagram Login Page title field seems to have changed, please make an issue on: https://github.com/Greenwolf/social_mapper
Instagram Timeout Error, session has expired and attempts to reestablish have failed

TKS!

**Comment by Greenwolf** [comment]
Hi, thank you for taking the time to raise the issue, I'll get on this as soon as I have a chance!

**Comment by Greenwolf** [comment]
Instagram is working, try changing your language to english on your account before running it? Or run through a UK/US VPN.

I need to verify facebook though.
