### ISSUE TITLE
Error Filling out Facebook Profiles [-]

### ISSUE THREAD

**Issue by shivgori** [Greenwolf/social_mapper#129]
I found this error please tell me what is this error

**Comment by Markeli** [comment]
I've gotten the same error.
The output is listed below:
```
[-] Error Filling out Facebook Profiles [-]
Message: invalid argument: can't kill an exited process

[-]


Results file: SM-Results/results-social-mapper.csv
HTML file: SM-Results/results-social-mapper.html

Task Duration: 0:00:01.380385
```

**Comment by Greenwolf** [comment]
Just checked and its working on real people, sometimes you can get errors on bill gates in the examples because he has a special "famous person" account that you can't friend etc.
