### ISSUE TITLE
Output: cookie debug 

### ISSUE THREAD

**Issue by pdelteil** [Greenwolf/social_mapper#131]
While running the following command, I only receive 'cookie debug' as output. 

> python3 social_mapper.py -f company -i "SpiderLabs" -m accurate -a -t strict
cookie debug

**Comment by Greenwolf** [comment]
Hi @Pdelteil, thats probally because its not a real company on LinkedIn, try on your own company that does exist.

**Comment by pkq2019** [comment]
same problem, while the company name exists in linked in ,   why ?

**Comment by Greenwolf** [comment]
Hi @pkq2019, i just tested and I don't get this issue when doing a company search on LinkedIn. Try changing your language to english if it isn't already as that could be affecting it? Otherwise I'll need more input/output
