### ISSUE TITLE
Not getting results from request

### ISSUE THREAD

**Issue by pdelteil** [Greenwolf/social_mapper#132]
I'm trying to retrieve data on linkedIn using this app. 

This is what I get :

![Screenshot from 2019-09-11 17-38-36](https://user-images.githubusercontent.com/20244863/64733715-9f69e180-d4bb-11e9-8dd8-bbf3d0a054a1.png)

No results are downloaded to the files. Why?

**Comment by Greenwolf** [comment]
So for a normal company in the real world this would work, but the issue here is you don't have connection degrees into the company so can't see anyone. Perhaps there is another way you can feed input into the tool?
