### ISSUE TITLE
Error Filling out Facebook Profiles

### ISSUE THREAD

**Issue by shivgori** [Greenwolf/social_mapper#134]
What is wrong in it

[-] Error Filling out Facebook Profiles [-]
cmd=['Xvfb', '-help']
OSError=[Errno 2] No such file or directory: 'Xvfb': 'Xvfb'
Program install error! 
[-]

Results file: SM-Results/results-social-mapper.csv
HTML file: SM-Results/results-social-mapper.html

**Comment by Greenwolf** [comment]
Is this on a OSX or Linux?

**Comment by diimdeep** [comment]
Hello, can you please clarify how to run it from Xquartz terminal ?

**Comment by diimdeep** [comment]
I will answer to myself, open /Applications/Utilities/XQuartz.app and use terminal from there.
