### ISSUE TITLE
In the future, will this software be able to search by name without photo?

### ISSUE THREAD

**Issue by Cvrew** [Greenwolf/social_mapper#136]
This search software searches based on name and photo. Will it be possible to search only with face photos in the future? Also, can you identify the name you need when you search? For example, if your real name is "Mark An", can you specify if you search by entering only "Mark"?

**Comment by Greenwolf** [comment]
Hi @Cvrew, Unfortunately not, for this to work you would have to scrape the entirety of the social media sites and have a giant database to search against. That's some nation state level stuff. 

The problem with using only the first name, is that there then is too many results to look through, so many that some won't be shown so it would be incredibly inaccurate.
