### ISSUE TITLE
Error Filling out Facebook Profiles

### ISSUE THREAD

**Issue by Palmus84** [Greenwolf/social_mapper#137]
[-] Error Filling out Facebook Profiles [-]
Message: timeouts

[-]
Please provide Twitter Login Credentials in the social_mapper.py file
Please provide Instagram Login Credentials in the social_mapper.py file
Please provide LinkedIn Login Credentials in the social_mapper.py file
Please provide VK (VKontakte) Login Credentials in the social_mapper.py file
Please provide Weibo Login Credentials in the social_mapper.py file
Please provide Douban Login Credentials in the social_mapper.py file

Results file: SM-Results/results-social-mapper.csv
HTML file: SM-Results/results-social-mapper.html

Task Duration: 0:00:07.547839

**Comment by Greenwolf** [comment]
Looks like you haven't added your credentials to the social_mapper.py file 😄

**Comment by Palmus84** [comment]
I did it, added credentials into social_mapper.py, username and password.

**Comment by Greenwolf** [comment]
and you still get the same error?

**Comment by Palmus84** [comment]
Yes, as I wrote.

**Comment by Greenwolf** [comment]
That's strange, can you give the full input and output please?

**Comment by Hassan033** [comment]
same issue
