### ISSUE TITLE
Error logging in.

### ISSUE THREAD

**Issue by SchellerCyberSecurity** [Greenwolf/social_mapper#138]
Yes I have validated all of my credentials within social mapper.py and yet I still get the following error when I try to run it. I am using Kali 2019 rolling completely updated.

root@SCSKali:~/social_mapper# python3 social_mapper.py -f company -i "Evil Corp LLC" -m fast -fb
Error logging in! Try changing language on social networks or verifying login data.
If a capcha is required to login (due to excessive attempts) it will keep failing, try using a VPN or running with the -s flag to show the browser, where you can manually solve the capcha.

I only have creds for twitter, ig, fb, and linkedin. I have used each one by itself and still get the same error. On OSX Catalina i keep getting can't login to LinkedIn and it stops, whether it is included or not.

**Comment by Greenwolf** [comment]
Hey @SchellerCyberSecurity, try using the '-s' option to show the browser, that way you can solve the login captacha in the browser

**Comment by Greenwolf** [comment]
Also I don't think it will work how you want it to on this, as you don't have any connection degrees to the company. Perhaps you should check out some of the other modes though?

**Comment by SchellerCyberSecurity** [comment]
I tried -s and no browser popped up, also I was looking through your other modes, what exactly are you talking about. Finally, why on OSX does it tell me 
[+] Authentication to LinkedIn Failed. 
When I am not attempting to use linkedin?

**Comment by Greenwolf** [comment]
-i, --input	: The company name, a CSV file, imagefolder or Social Mapper HTML file to feed into Social Mapper

**Comment by Greenwolf** [comment]
If -s isn't working its a problem with your selenium install. Try using a selenium test script to verify if its installed correctly.
