### ISSUE TITLE
received following error

### ISSUE THREAD

**Issue by technicaldada** [Greenwolf/social_mapper#139]
root@kali:~/social_mapper# python3 social_mapper.py -f imagefolder -i /root/social_mapper/Input-Examples/imagefolder -m fast -fb
[-] Error Filling out Facebook Profiles [-]
cmd=['Xvfb', '-help']
OSError=[Errno 2] No such file or directory: 'Xvfb': 'Xvfb'
Program install error!

**Comment by rootm0s** [comment]
From the setup folder:

> May need to install XQuartz to solve 'Xvfb' issues:
> https://www.xquartz.org/
> If you can't run 'Xvfb -help' after installation, try running from the XQuartz terminal:
> Applications > Utilities > XQuartz > Right Click in Dock > Terminal

https://github.com/Greenwolf/social_mapper/blob/master/setup/setup-mac.txt

**Comment by Greenwolf** [comment]
Thank you @rootm0s. This should have addressed the issue.
