### ISSUE TITLE
 Facebook Login Page loaded successfully [+] [-] Facebook Login Failed [-]

### ISSUE THREAD

**Issue by jisjose98** [Greenwolf/social_mapper#140]
Facebook Login Page loaded successfully [+]
[-] Facebook Login Failed [-]

even adding correct username and pasword in nano social_mapper.py

**Comment by Inf3r** [comment]
> Facebook Login Page loaded successfully [+]
> [-] Facebook Login Failed [-]
> 
> even adding correct username and pasword in nano social_mapper.py

Hey! have you follow the recommendations in README tips after perfom scan? for example changing some settings in the facebook session like the language system (set it to english)

**Comment by jisjose98** [comment]
sorry i did nt catch that can u xplain.In privacy my language is english

**Comment by Greenwolf** [comment]
@jisjose98, @Inf3r means this:
For Facebook, make sure the language of the account which you have provided credentials for is set to 'English (US)' for the duration of the run. Additionally make sure all of your accounts are working, and can be logged into without requiring 2 factor authentication.

**Comment by jisjose98** [comment]
Can u help me how to set the fb language to english.I set english in fb no other language is selected

**Comment by amir7587** [comment]
ImportError: No module named PyVirtualDisplay

**Comment by Greenwolf** [comment]
Facebook is verified as working. Try installing on OSX or Kali as these OS's have been checked.
