### ISSUE TITLE
Can't seem to log into FB

### ISSUE THREAD

**Issue by OSINT007** [Greenwolf/social_mapper#141]
Hello,

I followed all instructions. I put firefox and geckodriver on /usr/bin. I didn't have any issues running the installation. When I get to the part where I need to provide my credentials nothing shows up.

As instructed I run the command: 

`python3 social_mapper.py`

the following shows up:

root:~/social_mapper# python3 social_mapper.py
usage: social_mapper.py -f <format> -i <input> -m <mode> -t <threshold> <options>
social_mapper.py: error: the following arguments are required: -f/--format, -i/--input, -m/--mode

Anyone could help me with this?

**Comment by OSINT007** [comment]
Also,

I try to run the examples and I get this

python3 social_mapper.py -f imagefolder -i ./mytargets -m fast -fb -tw
Traceback (most recent call last):
  File "social_mapper.py", line 863, in <module>
    for filename in os.listdir(args.input):
FileNotFoundError: [Errno 2] No such file or directory: './mytargets/'

**Comment by Greenwolf** [comment]
@OSINT007 looks like you arn't providing the correct command line parameters. 

To enter your credentials you open the social_mapper.py file and put your username and passwords in the variables at the top of the file.

**Comment by OSINT007** [comment]
The credentials are properly input in the file. I still get the same error.
