### ISSUE TITLE
Trouble installing

### ISSUE THREAD

**Issue by clayton19979** [Greenwolf/social_mapper#144]
It seems every time i try and run the command "python -m pip install --no-cache-dir -r requirements.txt" it get's stuck on "Running setup.py install for dlib ... -" and will just eventually give me a whole lot of errors in red text. I have already installed all of the requirements to my knowledge. I'm running a kali linux machine that is up to date. Any help would be greatly apreciated. Thanks.

**Comment by Greenwolf** [comment]
@clayton19979 are you using a fresh kali box with nothing else installed on it? Sometimes other tools break the install process
