### ISSUE TITLE
Error Filling out Facebook Profiles [-]

### ISSUE THREAD

**Issue by Rootlente** [Greenwolf/social_mapper#147]
Error Filling out Facebook Profiles [-]
start error <EasyProcess cmd_param=['Xvfb', '-help'] cmd=['Xvfb', '-help'] oserror=[Errno 2] No such file or directory: 'Xvfb': 'Xvfb' return_code=None stdout="None" stderr="None" timeout_happened=False>

**Comment by Greenwolf** [comment]
@Rootlente are you using OSX?

**Comment by Rootlente** [comment]
no i  am using ubuntu

**Comment by Footsiefat** [comment]
Exactly the same problem...
`[-] Error Filling out Facebook Profiles [-]
start error <EasyProcess cmd_param=['Xvfb', '-help'] cmd=['Xvfb', '-help'] oserror=[Errno 2] No such file or directory: 'Xvfb': 'Xvfb' return_code=None stdout="None" stderr="None" timeout_happened=False>`
`       `:+ssssssssssssssssss+:`           ------------------- 
      -+ssssssssssssssssssyyssss+-         OS: Ubuntu 18.04.3 LTS x86_64 
    .ossssssssssssssssssdMMMNysssso.       Host: MacBook7,1 1.0 
   /ssssssssssshdmmNNmmyNMMMMhssssss/      Kernel: 4.15.0-74-generic 
  +ssssssssshmydMMMMMMMNddddyssssssss+     Uptime: 52 mins 
 /sssssssshNMMMyhhyyyyhmNMMMNhssssssss/    Packages: 2813 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Shell: bash 4.4.20 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Resolution: 1280x800 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   DE: Xfce 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   WM: Openbox 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   WM Theme: Nightmare 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Theme: Arc-Dark [GTK2/3] 
 /sssssssshNMMMyhhyyyyhdNMMMNhssssssss/    Icons: Numix-Circle [GTK2], Elementa 
  +sssssssssdmydMMMMMMMMddddyssssssss+     Terminal: xfce4-terminal 
   /ssssssssssshdmNNNNmyNMMMMhssssss/      Terminal Font: tewi2a 9 
    .ossssssssssssssssssdMMMNysssso.       CPU: Intel Core 2 Duo P8600 (2) @ 2. 
      -+sssssssssssssssssyyyssss+-         GPU: NVIDIA GeForce 320M 
        `:+ssssssssssssssssss+:`           Memory: 905MiB / 7714MiB 
            .-/+oossssoo+/-. 
                                                                   
`

**Comment by Footsiefat** [comment]
@Rootlente sudo apt-get install xvfb

**Comment by Greenwolf** [comment]
On Macbook use XQuartz Shell, on Linux install xvfb.
