### ISSUE TITLE
Cannot load main LinkedIn POST page

### ISSUE THREAD

**Issue by Kapalov** [Greenwolf/social_mapper#150]
Hi, I have an error: 

[!] Cannot load main LinkedIn POST page
loadpage debug
Traceback (most recent call last):
  File "social_mapper.py", line 755, in loadPage
    return emptybyte.join(response.readlines())
UnboundLocalError: local variable 'response' referenced before assignment

**Comment by Kapalov** [comment]
someone?

**Comment by Greenwolf** [comment]
Do you still have this issue with the most recent code? I added a suggestion to decode utf-8.

**Comment by Kapalov** [comment]
Yes, I added to, but still have error: 

sh-3.2# python3 social_mapper.py -f company -i "SpiderLabs" -m accurate -a -t strict
[!] Cannot load main LinkedIn POST page
loadpage debug
Traceback (most recent call last):
  File "social_mapper.py", line 755, in loadPage
    return emptybyte.join(response.readlines())
UnboundLocalError: local variable 'response' referenced before assignment

**Comment by Kapalov** [comment]
...

**Comment by Greenwolf** [comment]
Are you actually running it on -i "SpiderLabs" instead of a real company? SpiderLabs isnt a linkedin company, its just an example, so its probably returning nothing?

**Comment by Kapalov** [comment]
of course. I tried other companies, Google, Yandex etc... same error

**Comment by Kapalov** [comment]
it returns exactly this error: 
**[!] Cannot load main LinkedIn POST page**
loadpage debug
Traceback (most recent call last):
File "social_mapper.py", line 755, in loadPage
return emptybyte.join(response.readlines())
UnboundLocalError: local variable 'response' referenced before assignment

**Comment by Greenwolf** [comment]
Is anyone else having this problem? What OS/Python version are you running?

**Comment by archerwindy** [comment]
I have the same problem too. 
```
$ python3 --version
Python 3.8.1
```

**Comment by Kapalov** [comment]
It was problem with geckodriver. Fixed. Thank you.
