### ISSUE TITLE
Can't Run the program

### ISSUE THREAD

**Issue by OSINT007** [Greenwolf/social_mapper#151]
When I run the program I get the following error:

`[-] Error Filling out Facebook Profiles [-]
cmd=['Xvfb', '-help']
OSError=[Errno 2] No such file or directory: 'Xvfb': 'Xvfb'
Program install error! 
[-]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/easyprocess/__init__.py", line 227, in start
    env=self.env,
  File "/usr/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'Xvfb': 'Xvfb'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/easyprocess/__init__.py", line 180, in check_installed
    self.call()
  File "/usr/local/lib/python3.7/dist-packages/easyprocess/__init__.py", line 196, in call
    self.start().wait(timeout=timeout)
  File "/usr/local/lib/python3.7/dist-packages/easyprocess/__init__.py", line 232, in start
    raise EasyProcessError(self, 'start error')
easyprocess.EasyProcessError: start error <EasyProcess cmd_param=['Xvfb', '-help'] cmd=['Xvfb', '-help'] oserror=[Errno 2] No such file or directory: 'Xvfb': 'Xvfb' return_code=None stdout="None" stderr="None" timeout_happened=False>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "social_mapper.py", line 1046, in <module>
    peoplelist = fill_twitter(peoplelist)
  File "social_mapper.py", line 214, in fill_twitter
    TwitterfinderObject = twitterfinder.Twitterfinder(showbrowser)
  File "/root/social_mapper/modules/twitterfinder.py", line 16, in __init__
    display = Display(visible=0, size=(1600, 1024))
  File "/usr/local/lib/python3.7/dist-packages/pyvirtualdisplay/display.py", line 34, in __init__
    self._obj = self.display_class(
  File "/usr/local/lib/python3.7/dist-packages/pyvirtualdisplay/display.py", line 53, in display_class
    cls.check_installed()
  File "/usr/local/lib/python3.7/dist-packages/pyvirtualdisplay/xvfb.py", line 40, in check_installed
    ubuntu_package=PACKAGE).check_installed()
  File "/usr/local/lib/python3.7/dist-packages/easyprocess/__init__.py", line 182, in check_installed
    raise EasyProcessCheckInstalledError(self)
easyprocess.EasyProcessCheckInstalledError: cmd=['Xvfb', '-help']
OSError=[Errno 2] No such file or directory: 'Xvfb': 'Xvfb'
Program install error!`

Any help would be amazing!

**Comment by Inf3r** [comment]
> When I run the program I get the following error:
> 
> `[-] Error Filling out Facebook Profiles [-]
> cmd=['Xvfb', '-help']
> OSError=[Errno 2] No such file or directory: 'Xvfb': 'Xvfb'
> Program install error!
> [-]
> Traceback (most recent call last):
> File "/usr/local/lib/python3.7/dist-packages/easyprocess/**init**.py", line 227, in start
> env=self.env,
> File "/usr/lib/python3.7/subprocess.py", line 800, in **init**
> restore_signals, start_new_session)
> File "/usr/lib/python3.7/subprocess.py", line 1551, in _execute_child
> raise child_exception_type(errno_num, err_msg, err_filename)
> FileNotFoundError: [Errno 2] No such file or directory: 'Xvfb': 'Xvfb'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "/usr/local/lib/python3.7/dist-packages/easyprocess/**init**.py", line 180, in check_installed
> self.call()
> File "/usr/local/lib/python3.7/dist-packages/easyprocess/**init**.py", line 196, in call
> self.start().wait(timeout=timeout)
> File "/usr/local/lib/python3.7/dist-packages/easyprocess/**init**.py", line 232, in start
> raise EasyProcessError(self, 'start error')
> easyprocess.EasyProcessError: start error <EasyProcess cmd_param=['Xvfb', '-help'] cmd=['Xvfb', '-help'] oserror=[Errno 2] No such file or directory: 'Xvfb': 'Xvfb' return_code=None stdout="None" stderr="None" timeout_happened=False>
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "social_mapper.py", line 1046, in
> peoplelist = fill_twitter(peoplelist)
> File "social_mapper.py", line 214, in fill_twitter
> TwitterfinderObject = twitterfinder.Twitterfinder(showbrowser)
> File "/root/social_mapper/modules/twitterfinder.py", line 16, in **init**
> display = Display(visible=0, size=(1600, 1024))
> File "/usr/local/lib/python3.7/dist-packages/pyvirtualdisplay/display.py", line 34, in **init**
> self._obj = self.display_class(
> File "/usr/local/lib/python3.7/dist-packages/pyvirtualdisplay/display.py", line 53, in display_class
> cls.check_installed()
> File "/usr/local/lib/python3.7/dist-packages/pyvirtualdisplay/xvfb.py", line 40, in check_installed
> ubuntu_package=PACKAGE).check_installed()
> File "/usr/local/lib/python3.7/dist-packages/easyprocess/**init**.py", line 182, in check_installed
> raise EasyProcessCheckInstalledError(self)
> easyprocess.EasyProcessCheckInstalledError: cmd=['Xvfb', '-help']
> OSError=[Errno 2] No such file or directory: 'Xvfb': 'Xvfb'
> Program install error!`
> 
> Any help would be amazing!

Hey! try with:
"apt update && apt install xvfb && pip3 install pyvirtualdisplay && pip install pyvirtualdisplay"
(without cuotes)

**Comment by Greenwolf** [comment]
I assume this is fixed, thank you @Inf3r

**Comment by Inf3r** [comment]
> I assume this is sorted, thank you @Inf3r

I really long for a contemporary version of this project, we miss you green! come back soon
