### ISSUE TITLE
Instagram Login Page error

### ISSUE THREAD

**Issue by peha2407** [Greenwolf/social_mapper#154]
Hi Greenwolf

Thanks for this program! When I want to run it with instagram, the following error appears: 
"Instagram Login Page title field seems to have changed, please make an issue on: https://github.com/Greenwolf/social_mapper"
What am I doing wrong?

**Comment by Greenwolf** [comment]
Is this still a problem? No one else has flagged instagram as not working?

**Comment by F4310** [comment]
I have a problem with Instagram login "Instagram Login Page title field seems to have changed....".
Same with Twitter.

**Comment by Greenwolf** [comment]
> I have a problem with Instagram login "Instagram Login Page title field seems to have changed....".
> I believe the error is on the line 90
> "searchbar = self.driver.find_element_by_xpath("//input[@Placeholder='Search']")"
> You must change the word "Search" according to the yours Instagram text language.

So could this be solved by asking users to change their accounts to English temporarily?

**Comment by F4310** [comment]
That's right
