### ISSUE TITLE
Face recognition module issue

### ISSUE THREAD

**Issue by DogSalary911** [Greenwolf/social_mapper#155]
Hi, 

Thanks for sharing this great tool. I wanted to test it, but unfortunately i ran into some problem while trying to launch it.

After installing both Geckodriver and Selenium, and installing all the requirements, the script still won't launch and gives me this error : 

RuntimeError: Unable to open C:\Users\<user>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\face_recognition_models\models\shape_predictor_68_face_landmarks.dat

While i'm CERTAIN the file is in the right folder, and i reinstalled the face recognition module, I still can't use your script. 

Would anyone help me on this ?

**Comment by Greenwolf** [comment]
I would recommend using Linux not Windows, as i dont think anyone has managed to get this working on Windows yet.
