### ISSUE TITLE
[-] Error Filling out Facebook Profiles [-]

### ISSUE THREAD

**Issue by animosfive** [Greenwolf/social_mapper#156]
hi .i need help to Solvod this Problem 
i try to Start Social_Mapper Normally By Taping this Command :
sudo python3 social_mapper.py -f imagefolder -i /home/kali/Desktop/social_mapper/Input-Examples/imagefolder -m fast -fb

But Get This Error and This Result :

[-] Error Filling out Facebook Profiles [-]
Message: Unable to find a matching set of capabilities

[-]

Results file: SM-Results/results-social-mapper.csv
HTML file: SM-Results/results-social-mapper.html

***please help***AND*** Tanks

**Comment by velbert7** [comment]
same issue

**Comment by animosfive** [comment]
same issue like what?

**Comment by Greenwolf** [comment]
Facebook is working right now, try the most recent version please. use the --debug flag for more information to see if any potential profiles are being returned in an array.
