### ISSUE TITLE
LinkedIn Timeout Error, session has expired and attempts to reestablish have failed

### ISSUE THREAD

**Issue by Adastra-thw** [Greenwolf/social_mapper#161]
Hello, 
After running this command:
python3 social_mapper.py -f imagefolder -i ./images -m fast -li 

I get this results:

LinkedIn Login Page title field seems to have changed, please make an issue on: https://github.com/Greenwolf/social_mapper
LinkedIn Check 1/1 : 0                                LinkedIn Login Page title field seems to have changed, please make an issue on: https://github.com/Greenwolf/social_mapper
LinkedIn Timeout Error, session has expired and attempts to reestablish have failed

Seems that the login page in LinkedIn now is not the same as expected in the project. Anyone else having this issue?

**Comment by Greenwolf** [comment]
LinkedIn is working right now.
