### ISSUE TITLE
Instagram Timeout Error

### ISSUE THREAD

**Issue by srzlucifer** [Greenwolf/social_mapper#163]
[+] Instagram Login Page loaded successfully [+]
[-] Instagram Login Failed [-]

Instagram Check 1/1 : 2                                
[+] Instagram Login Page loaded successfully [+]
[-] Instagram Login Failed [-]

Instagram Timeout Error, session has expired and attempts to reestablish have failed
Task Duration: 0:01:49.159393

Please, how to fix it?

**Comment by Greenwolf** [comment]
Instagram is now working.
