### ISSUE TITLE
Twitter Login Page title field seems to have changed

### ISSUE THREAD

**Issue by newmentos** [Greenwolf/social_mapper#164]
`Twitter Login Page title field seems to have changed, please make an issue on: https://github.com/Greenwolf/social_mapper`

**Comment by tanguy-opendsi** [comment]
up

**Comment by IssouLinux** [comment]
I have the same issue

**Comment by tanguy-opendsi** [comment]
Same for meet too

**Comment by NicolasDarcis** [comment]
Same here. Following.

**Comment by Greenwolf** [comment]
Twitter and LinkedIn are both working now.
