### ISSUE TITLE
permission error 13 help me unable to run this social mapper

### ISSUE THREAD

**Issue by DoctorBiswajit** [Greenwolf/social_mapper#165]
![kali help](https://user-images.githubusercontent.com/63886963/79623758-9caf2900-813b-11ea-8cc2-dcd6f2384c77.png)

**Comment by peipeiWU1996-CV** [comment]
maybe the permission of the file is something wrong?

**Comment by Greenwolf** [comment]
Looks like you've spelled Input_Examples as Inpt_Examples
