### ISSUE TITLE
Douban Is Not Working

### ISSUE THREAD

**Issue by peipeiWU1996-CV** [Greenwolf/social_mapper#166]
Hi i am trying to use Socail mapper and it appears HTTP 418 Error and i am not sure whether it logins into douban or not. can you give me some suggestion? Many thanks

**Comment by Greenwolf** [comment]
Hi @peipeiWU1996-CV, I think the site has changed. It seems like the first part of the mobile number needs to be clicked to be changed, and if you want to login with email instead you need to click on this. I also can't seem to find where I sign up to the service, so I can't make an account to verify anything. 

If anyone can assist it would it would be appreciated.

**Comment by alexsok-bit** [comment]
I think this the fix will be work. But I haven't valid username and password for completely check this.

**Comment by peipeiWU1996-CV** [comment]
Hi

I will check it today. So sorry to reply too late. I spent all my time on
my master dissertation. I will give you feedback tomorrow.

Best wishes
Peipei

**Comment by alexsok-bit** [comment]
my a PR is not merged now. but you can clone a forked repository from my account and switch branch to `issue/166`

**Comment by peipeiWU1996-CV** [comment]
Sorry, I did not run it well. Give me some time to check the environment.
It should be working now. I will write down the result for you. And I will
update it on GitHub, also an email to u.

Many thanks!

**Comment by Greenwolf** [comment]
Hi @alexsok-bit, i'm so sorry I missed your merge and just pushed a bunch of fixes for other things, are you able to resubmit for me? Thank you for taking the time!!

**Comment by alexsok-bit** [comment]
I resolved conflicts.

**Comment by alexsok-bit** [comment]
@Greenwolf Are you seen my PR?

**Comment by alexsok-bit** [comment]
@peipeiWU1996-CV fixes for the douban is merged into master by now. update your project files and try again.

**Comment by Greenwolf** [comment]
Please reopen if Douban is still not working
