### ISSUE TITLE
Installation issue 

### ISSUE THREAD

**Issue by AlistairXX** [Greenwolf/social_mapper#169]
It seems every time i try and run the command "python -m pip install --no-cache-dir -r requirements.txt" it get's stuck on "Running setup.py install for dlib ... -" and will just eventually give me a whole lot of errors in red text. I have already installed all of the requirements to my knowledge. I'm running a kali linux machine that is up to date. Any help would be greatly apreciated. Thanks...

This is a fresh install of Kali Linux...tried on virtual box as well as on a seperate machine running kali.

**Comment by Zircoz** [comment]
What's the error?

**Comment by ContactDev913** [comment]
@AlistairXX Install CMake. Then try. On my end it is telling me the same thing but it tells me to install CMake and try again.

**Comment by Greenwolf** [comment]
Should be solved by running CMake, thanks @ContactDev913
