### ISSUE TITLE
Issue while doing a Linkedin scan: selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: [id="session_key-login"]

### ISSUE THREAD

**Issue by IssouLinux** [Greenwolf/social_mapper#171]
Hello,

First of all, congratulations for your work!   
And now, here is my feedback:
When I launch a scan on linkedin, I got this error:

> [+] LinkedIn Login Page loaded successfully [+]
> Traceback (most recent call last):
>   File "social_mapper.py", line 1123, in <module>
>     peoplelist = fill_linkedin(peoplelist)
>   File "social_mapper.py", line 384, in fill_linkedin
>     LinkedinfinderObject.doLogin(linkedin_username,linkedin_password)
>   File "/home/seifer/HackTools/SocEngTools/SocialMapper/modules/linkedinfinder.py", line 30, in doLogin
>     lnkUsername = self.driver.find_element_by_id("session_key-login")
>   File "/home/seifer/.local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 360, in find_element_by_id
>     return self.find_element(by=By.ID, value=id_)
>   File "/home/seifer/.local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
>     'value': value})['value']
>   File "/home/seifer/.local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
>     self.error_handler.check_response(response)
>   File "/home/seifer/.local/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
>     raise exception_class(message, screen, stacktrace)
> selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: [id="session_key-login"]

How could I fix it?

**Comment by Greenwolf** [comment]
This is a selenium installation issue, try following the installation instructions for Kali or OSX as they are verified as working.
