### ISSUE TITLE
Error logging in! 

### ISSUE THREAD

**Issue by Banthex** [Greenwolf/social_mapper#172]
Hello,

social_mapper cant login. Credentials are same as i tested on browser.
Flag -s dont work ( no browser starts)
Have credentials for fb, ig, pin

>Error logging in! Try changing language on social networks or verifying login data.
If a capcha is required to login (due to excessive attempts) it will keep failing, try using a VPN or running with the -s flag to show the browser, where you can manually solve the capcha.

Greetings

**Comment by insaankaputla** [comment]
remove @gmail.com from your username

**Comment by Greenwolf** [comment]
All sites are now logging in correctly with the full email address
