### ISSUE TITLE
Twitter is Not login 

### ISSUE THREAD

**Issue by chrysl666** [Greenwolf/social_mapper#174]
I have a login problem using twitter , even settings using English  Language .
"Twitter Login Page title field seems to have changed, please make an issue on: https://github.com/Greenwolf/social_mapper"

Anyone have fix this ? 

tnx !

**Comment by NicolasDarcis** [comment]
I have the same issue.
Following.

**Comment by Deepi-cyber** [comment]
yes same issue again..and for facebook it was reestablishing session again and again

**Comment by Greenwolf** [comment]
Twitter and Facebook are both working again in the latest update
