### ISSUE TITLE
How does the name of an image in the imagefolder affect searches?

### ISSUE THREAD

**Issue by JackHarboraa** [Greenwolf/social_mapper#177]
I want to run a search but I do not know the name of the target, I only have an image.

I noticed that if I name the image woman.jpg the name woman affects the search results.
Is there an option to turn off this criteria and search solely based on the image and not the name?

**Comment by Deepi-cyber** [comment]
yes i have the same query as well kindly answer

**Comment by Greenwolf** [comment]
Social Mapper doesn't support this. Try ClearView AI 😃:
https://en.wikipedia.org/wiki/Clearview_AI

**Comment by JackHarboraa** [comment]
Haha good one @Greenwolf, anyways thanks for the quick reply!

**Comment by Deepi-cyber** [comment]
Will you be able to solve twitter and facebook issues.For twitter its
saying login page changed and not picking any data and for facebook  its
reestablishing session.kindly solve these issues.
