### ISSUE TITLE
No result

### ISSUE THREAD

**Issue by insaankaputla** [Greenwolf/social_mapper#179]
[+] Facebook Login Page loaded successfully [+]
[+] Facebook Login Success [+]

Facebook Check 1/1 : Linus Torvalds                                

Results file: SM-Results/results-social-mapper.csv
HTML file: SM-Results/results-social-mapper.html

result files are empty, why ?

**Comment by Greenwolf** [comment]
Fixed in latest update

**Comment by azamet90** [comment]
> Fixed in latest update

today i tested and i have exactly the same problem!
https://github.com/Greenwolf/social_mapper/issues/198 check my topic pls! thanks.
