### ISSUE TITLE
[-] Error Filling out Facebook Profiles [-]--------

### ISSUE THREAD

**Issue by mamun626** [Greenwolf/social_mapper#180]
plz help..........
[-] Error Filling out Facebook Profiles [-]
Message: Unable to find a matching set of capabilities
[-]

Results file: SM-Results/results-social-mapper.csv
HTML file: SM-Results/results-social-mapper.html

Task Duration: 0:00:06.172560

**Comment by Greenwolf** [comment]
There is a problem with your selenium installation, troubleshoot this using a selenium test script, or follow the installation instructions for OSX or Kali Linux.
