### ISSUE TITLE
can anyone help with that plz...

### ISSUE THREAD

**Issue by mamun626** [Greenwolf/social_mapper#182]
[-] **_**Error Filling out Facebook Profiles**_** [-]
Message: invalid argument: can't kill an exited process

[-]

Results file: SM-Results/results-social-mapper.csv
HTML file: SM-Results/results-social-mapper.html

Task Duration: 0:00:04.020666

**Comment by Greenwolf** [comment]
Sounds like you have an install problem, try using OSX or Kali Linux in a virtual machine.
