### ISSUE TITLE
Social Mapper giving no result.

### ISSUE THREAD

**Issue by themayanksingh** [Greenwolf/social_mapper#183]
I am trying to look for **Jennifer Lawrence** using following command but, I get no result.
Command Given- `python3 social_mapper.py -f imagefolder -i /home/bsm/kali/apps/htools/social_mapper/Input-Examples/imagefolder/ -m accurate -t strict -a`
Image used for searching _Jennifer Lawrence_ profile-

![Jennifer Lawrence](https://user-images.githubusercontent.com/57923371/86426088-59923a00-bcd6-11ea-9e39-a058f15b3874.jpg)

Results-
[SM-Results.zip](https://github.com/Greenwolf/social_mapper/files/4867508/SM-Results.zip)

**Comment by Greenwolf** [comment]
Use the input examples to test if you have an install problem or the person has no public accounts.
