### ISSUE TITLE
ModuleNotFoundError: No module named 'facebook'

### ISSUE THREAD

**Issue by presmedia002** [Greenwolf/social_mapper#185]
Traceback (most recent call last):
  File "social_mapper.py", line 11, in <module>
    import facebook
ModuleNotFoundError: No module named 'facebook'

PS: I have pip installed facebook-sdk and facebook

**Comment by Greenwolf** [comment]
Sounds like your python and your pip are unlinked, do you have multiple versions of python? are you using python 3 for social mapper and python 2 for pip?
