### ISSUE TITLE
Error logging in !

### ISSUE THREAD

**Issue by asilhansahin** [Greenwolf/social_mapper#194]
Hello dear .

![image](https://user-images.githubusercontent.com/70915355/92481902-a96a1180-f1ef-11ea-896e-1c2d221d04a8.png)

I running this command : 
`python3 social_mapper.py -f company -i "SpiderLabs" -m accurate -a -t strict
`
I am encountering this command : 
`Error logging in! Try changing language on social networks or verifying login data.
If a capcha is required to login (due to excessive attempts) it will keep failing, try using a VPN or running with the -s flag to show the browser, where you can manually solve the capcha.
`

How can i fix this problem . Thx in advance,

**Comment by Greenwolf** [comment]
Make sure you have the languages set the English, Also SpiderLabs isn't a real company to practise with on LinkedIn, try google or something instead
