### ISSUE TITLE
Error Filling out Facebook Profiles / not clickable

### ISSUE THREAD

**Issue by MarcelTopTop** [Greenwolf/social_mapper#205]
Hey,

everything works fine with social mapper (instagram, twitter, LinkdIn...). It's just for Facebook, when it tries to log in there's a cookies pop up window that appears (accept all cookies).  Because of this pop up window it can not login. This is the error message given:

_[+] Facebook Login Page loaded successfully [+]
[-] Error Filling out Facebook Profiles [-]
Message: Element < button id="loginbutton" class="_42ft _4jy0 _52e0 _4jy6 _4jy1 selected _51sy" name="login" type="submit" > is not clickable at point (640,341)  because another element < div class="_9fwn" > obscures it_

Do you have any idea how to get around this?

Thank you for your help

M.

**Comment by Greenwolf** [comment]
Hi @MarcelTopTop, if you use the -s and the -w flags, it will wait for you to press enter after login. So you can manually accept notifications or messages, and correct your login or manually login if there are any problems. 

I hope this resolves your issue!

**Comment by MarcelTopTop** [comment]
Hi, the problem is that it happens before the login which results in it being unable to login.

I'm quiet new in this so I'm sorry if it's just something stupid I oversaw, thank you for taking your time with this.
