### ISSUE TITLE
What to do if I don't know the name of the person?

### ISSUE THREAD

**Issue by CaptainBearFace** [Greenwolf/social_mapper#208]
I don't know the names of people I'm searching for, I only have their pictures. I'm primarily focusing on instagram and to a lesser extent Facebook. It seems to me that having a name is a big part in fetching results, but this is a problem for me. Can social mapper work properly without a name?

**Comment by Greenwolf** [comment]
No sorry @CaptainBearFace, social mapper isn't the right tool for this.
